name: file_entry
description: "A package for displaying a single file on the file system and listing options."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  file_preview: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

