name: file_entry
description: "A package for displaying a single file on the file system and listing options."
version: 0.0.2+1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  path: 1.8.3
  file_preview: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

