name: file_manager
description: "Sophisticated and modern material design file manager"
publish_to: 'none'

version: 0.0.2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_entry: ^0.0.3
  app_base: ^0.0.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
