name: fast_rss_data
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-323.2.beta

# Add regular dependencies here.
dependencies:
  flutter_rust_bridge: ^1.62.1
  ffi: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  ffigen: ^13.0.0
  lints: ^4.0.0
  test: ^1.24.0
