[package]
name = "fast_rss_data_fl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
bitcode = "*"
fast_rss_data = { version = "0.1.0", path = "../../../rust/fast_rss_data" }
flutter_rust_bridge = "=2.2.0"
zstd = "*"
