[package]
name = "rss-server"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
fast_rss_data = { version = "0.1.0", path = "../fast_rss_data" }
log = "0.4.22"
reqwest = "0.12.5"
roxmltree = "0.20.0"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
