name: assets
description: "Reusable assets."
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg_icons: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - packages/assets/icons/generic_file.svg
