name: app_base
description: "Components and styles at the base of a derdilla-app"
version: 0.0.2+2
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
