name: rewordle
description: "A custom frontend for the classic wordle game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

