name: file_preview
description: "A package to create low resolution previews and icons for files."
version: 0.0.1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  assets: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
