name: file_preview
description: "A package to create low resolution previews and icons for files."
version: 0.0.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.2.0'

dependencies:
  flutter:
    sdk: flutter
  path: 1.9.0
  assets: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
