name: Build and release calculator for Android
on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    steps:                                          
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install dependencies
      - uses: nttld/setup-ndk@v1
        name: Install NDK
        id: setup-ndk
        with:
          ndk-version: "r26b"
          add-to-path: true
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.16.3
      - name: setup rust ndk builds
        run: |
          cargo install cargo-ndk
          rustup target add \
               aarch64-linux-android \
               armv7-linux-androideabi \
               x86_64-linux-android \
               i686-linux-android

      - uses: actions/checkout@v4
      - name: Build
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        working-directory: ./apps/calculator
        run: |
          flutter pub get
          flutter build apk --debug --split-per-abi

      - uses: actions/upload-artifact@v4
        with:
          path: "apps/calculator/build/app/outputs/apk/debug/*.apk"
          compression-level: 2
